# Generated by Django 4.2 on 2023-04-28 13:50

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_title', models.CharField(db_index=True, max_length=350, null=True, verbose_name='عنوان (در tag title)')),
                ('h1_title', models.CharField(db_index=True, max_length=350, null=True, verbose_name='عنوان (در tag h1)')),
                ('meta_description', models.TextField(null=True, verbose_name='متا description')),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, unique=True, verbose_name='ادرس url')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='متن')),
                ('short_description', models.TextField(null=True, verbose_name='توضیحات کوتاه')),
                ('thumbnail', models.ImageField(upload_to='thumbnails', verbose_name='عکس بند انگشتی')),
                ('og_type', models.CharField(blank=True, max_length=300, null=True)),
                ('og_title', models.CharField(blank=True, max_length=300, null=True)),
                ('og_desc', models.CharField(blank=True, max_length=300, null=True)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='thumbnails')),
                ('og_url', models.CharField(blank=True, max_length=300, null=True)),
                ('canonical_url', models.CharField(blank=True, max_length=300, null=True)),
                ('published', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='زمان انتشار')),
                ('status', models.CharField(choices=[('d', 'پیش نویس'), ('p', 'منتشر شده')], max_length=1, null=True, verbose_name='وضعیت')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='زمان ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='زمان آپدیت')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
            },
        ),
        migrations.CreateModel(
            name='ArticleCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=350, verbose_name='عنوان')),
                ('url_title', models.CharField(max_length=350, null=True, verbose_name='عنوان در url')),
                ('meta_description', models.TextField(null=True, verbose_name='متا description')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='زمان ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='زمان آپدیت')),
            ],
            options={
                'verbose_name': 'دسته بندی مقاله',
                'verbose_name_plural': 'دسته بندی مقالات',
            },
        ),
        migrations.CreateModel(
            name='ArticleComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=250, verbose_name='نام')),
                ('body', models.TextField(verbose_name='متن')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='زمان ایجاد شده')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='زمان آپدیت شده')),
                ('is_show', models.BooleanField(default=True, verbose_name='وضعیت نمایش')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_comment', to='blog.article', verbose_name='مقاله مرتبط')),
            ],
            options={
                'verbose_name': 'کامنت ها',
                'verbose_name_plural': 'کامنت',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_category', to='blog.articlecategorymodel', verbose_name='دسته بندی'),
        ),
    ]
