# Generated by Django 4.2 on 2023-04-28 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_url', models.CharField(max_length=350, verbose_name='آدرس مبدأ')),
                ('destination_url', models.CharField(max_length=350, verbose_name='آدرس مقصد')),
                ('status_code', models.CharField(choices=[('301', '301'), ('302', '302'), ('410', '410')], max_length=250, verbose_name='نوع ریدایرکت')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='زمان ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='زمان آپدیت')),
            ],
            options={
                'verbose_name': 'ریدایرکت',
                'verbose_name_plural': 'ریدایرکت ها',
            },
        ),
    ]
